[toolchain]
anchor_version = "0.29.0"
solana_version = "1.18.3"

[features]
seeds = false
skip-lint = false

[programs.devnet]
example-program = "3BxNMJ7VSjtVkrDLDY93D214MmQPBEx9LvTXu5gKxJkX"
guardian_program = "EFi3XHwSt8gkMP8DpMdF719YNtZYAqmazcn2gYWCWg7K"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = ".keypairs/deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
